version: "3.7"
services:
 
  hub:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443        
      - 4444:4444
      - 4445:4445
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
    networks:
      - prodnetwork
    
    chrome:
    image: selenium/node-chrome-debug
    container_name: web-chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
      SE_EVENT_BUS_HOST: selenium
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
      SE_NODE_MAX_SESSIONS: 10
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    links:
      - hub
    networks:
      - prodnetwork
    
    firefox:
    image: selenium/node-firefox-debug
    container_name: web-firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
    links:
      - hub
    networks:
      - prodnetwork
