#Docker file for building the image for Spring boot application
FROM ubuntu as ubuntu_os

FROM maven:3.8-jdk-11 as maven_build

ENV myVariable = "This is myVaraible value from Dockerfile"
ENV hostIP = ""

#WORKDIR /app
VOLUME /tmp

COPY pom.xml .    
COPY src ./src
COPY src /app
COPY target /app
#RUN mvn clean package install -Dmaven.test.skip=true && rm -r target

ARG JAR_NAME="hello-karate-1.0.2-SNAPSHOT"
# To package the application
#COPY src ./src
RUN mvn install -Dmaven.test.skip=true

########run stage########
#FROM openjdk:11
WORKDIR ./
Run mkdir -p testfolder
ARG JAR_NAME="hello-karate-1.0.2-SNAPSHOT"

WORKDIR '/target'
COPY ./target/ /app/
#COPY ./target/hello-karate-1.0.2-SNAPSHOT.jar hello-karate-1.0.2-SNAPSHOT.jar

#run the app
ENV JAVA_OPTS ""
#EXPOSE 8081
#CMD [ "bash", "-c", "java ${JAVA_OPTS} -jar hello-karate-1.0.2-SNAPSHOT.jar"]
ENV hostIP = ""
